"""Add RBAC support to users table

Revision ID: 3afcca7d5822
Revises: 36e245a25e24
Create Date: 2025-07-13 11:12:07.533671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3afcca7d5822'
down_revision = '36e245a25e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courseware', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间')

    with op.batch_alter_table('dashboard_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='统计ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('statistic_date',
               existing_type=sa.DATE(),
               comment='统计日期',
               existing_nullable=False)
        batch_op.alter_column('total_online_devices',
               existing_type=mysql.INTEGER(),
               comment='在线设备数',
               existing_nullable=True)
        batch_op.alter_column('total_offline_devices',
               existing_type=mysql.INTEGER(),
               comment='离线设备数',
               existing_nullable=True)
        batch_op.alter_column('total_error_devices',
               existing_type=mysql.INTEGER(),
               comment='错误设备数',
               existing_nullable=True)
        batch_op.alter_column('total_courses_delivered',
               existing_type=mysql.INTEGER(),
               comment='课程投递数',
               existing_nullable=True)
        batch_op.alter_column('total_tours_conducted',
               existing_type=mysql.INTEGER(),
               comment='导览进行数',
               existing_nullable=True)
        batch_op.alter_column('total_interactions',
               existing_type=mysql.INTEGER(),
               comment='交互总数',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('education_settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='设置ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('equipment_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='设备ID',
               existing_nullable=False)
        batch_op.alter_column('screen_sync_mode',
               existing_type=mysql.ENUM('auto', 'manual', 'off'),
               comment='屏幕同步模式',
               existing_nullable=True)
        batch_op.alter_column('ai_platform',
               existing_type=mysql.VARCHAR(length=50),
               comment='AI平台',
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(length=50),
               comment='学科',
               existing_nullable=True)
        batch_op.alter_column('voice_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='语音类型',
               existing_nullable=True)
        batch_op.alter_column('robot_action',
               existing_type=mysql.VARCHAR(length=50),
               comment='机器人动作',
               existing_nullable=True)
        batch_op.alter_column('hand_recognition',
               existing_type=mysql.TINYINT(display_width=1),
               comment='手势识别',
               existing_nullable=True)
        batch_op.alter_column('interactive_qa',
               existing_type=mysql.TINYINT(display_width=1),
               comment='互动问答',
               existing_nullable=True)
        batch_op.alter_column('navigation_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment='导航模式',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(),
               comment='更新者ID',
               existing_nullable=True)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=50),
               comment='设备唯一标识，如G1-EDU-001',
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               comment='设备所在位置',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               comment='设备当前状态',
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=50),
               comment='IP地址',
               existing_nullable=True)
        batch_op.alter_column('last_active',
               existing_type=mysql.DATETIME(),
               comment='最后活跃时间',
               existing_nullable=True)
        batch_op.alter_column('usage_rate',
               existing_type=mysql.VARCHAR(length=10),
               comment='使用率',
               existing_nullable=True)
        batch_op.alter_column('is_offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='离线状态: 1-离线, 0-在线',
               existing_nullable=True)
        batch_op.alter_column('has_error',
               existing_type=mysql.TINYINT(display_width=1),
               comment='错误状态: 1-有错误, 0-正常',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)

    with op.batch_alter_table('navigation_points', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='点位ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('equipment_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='设备ID',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               comment='点位名称',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment='点位描述',
               existing_nullable=True)
        batch_op.alter_column('x_position',
               existing_type=mysql.FLOAT(),
               comment='X坐标',
               existing_nullable=False)
        batch_op.alter_column('y_position',
               existing_type=mysql.FLOAT(),
               comment='Y坐标',
               existing_nullable=False)
        batch_op.alter_column('rotation',
               existing_type=mysql.FLOAT(),
               comment='朝向角度',
               existing_nullable=True)
        batch_op.alter_column('enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_nullable=True)

    with op.batch_alter_table('navigation_settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='设置ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('equipment_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='设备ID',
               existing_nullable=False)
        batch_op.alter_column('scene_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='场景类型',
               existing_nullable=True)
        batch_op.alter_column('ai_platform',
               existing_type=mysql.VARCHAR(length=50),
               comment='AI平台',
               existing_nullable=True)
        batch_op.alter_column('voice_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='语音类型',
               existing_nullable=True)
        batch_op.alter_column('scene_prompt',
               existing_type=mysql.TEXT(),
               comment='场景提示词',
               existing_nullable=True)
        batch_op.alter_column('object_recognition',
               existing_type=mysql.TINYINT(display_width=1),
               comment='对象识别',
               existing_nullable=True)
        batch_op.alter_column('recognition_action',
               existing_type=mysql.VARCHAR(length=50),
               comment='识别动作',
               existing_nullable=True)
        batch_op.alter_column('auto_follow',
               existing_type=mysql.TINYINT(display_width=1),
               comment='自动跟随',
               existing_nullable=True)
        batch_op.alter_column('patrol_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment='巡逻模式',
               existing_nullable=True)
        batch_op.alter_column('navigation_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment='导航模式',
               existing_nullable=True)
        batch_op.alter_column('emergency_alert',
               existing_type=mysql.TINYINT(display_width=1),
               comment='紧急报警',
               existing_nullable=True)
        batch_op.alter_column('alert_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment='报警模式',
               existing_nullable=True)
        batch_op.alter_column('robot_speed',
               existing_type=mysql.INTEGER(),
               comment='机器人速度(0-100)',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(),
               comment='更新者ID',
               existing_nullable=True)

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='日志ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=255),
               comment='操作描述',
               existing_nullable=False)
        batch_op.alter_column('details',
               existing_type=mysql.TEXT(),
               comment='操作详情',
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=50),
               comment='IP地址',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True, comment='角色ID'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('real_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='真实姓名',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=100),
               comment='邮箱地址',
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机号码',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'operator', 'viewer'),
               comment='用户角色',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               comment='用户状态: 1-启用, 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               comment='最后登录时间',
               existing_nullable=True)
        batch_op.alter_column('login_count',
               existing_type=mysql.INTEGER(),
               comment='登录次数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间')
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
        batch_op.alter_column('login_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='登录次数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后登录时间',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='用户状态: 1-启用, 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'operator', 'viewer'),
               comment=None,
               existing_comment='用户角色',
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='手机号码',
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=120),
               comment=None,
               existing_comment='邮箱地址',
               existing_nullable=True)
        batch_op.alter_column('real_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='真实姓名',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('role_id')

    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='IP地址',
               existing_nullable=True)
        batch_op.alter_column('details',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='操作详情',
               existing_nullable=True)
        batch_op.alter_column('action',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='操作描述',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='日志ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('navigation_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='更新者ID',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('robot_speed',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='机器人速度(0-100)',
               existing_nullable=True)
        batch_op.alter_column('alert_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='报警模式',
               existing_nullable=True)
        batch_op.alter_column('emergency_alert',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='紧急报警',
               existing_nullable=True)
        batch_op.alter_column('navigation_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='导航模式',
               existing_nullable=True)
        batch_op.alter_column('patrol_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='巡逻模式',
               existing_nullable=True)
        batch_op.alter_column('auto_follow',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='自动跟随',
               existing_nullable=True)
        batch_op.alter_column('recognition_action',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='识别动作',
               existing_nullable=True)
        batch_op.alter_column('object_recognition',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='对象识别',
               existing_nullable=True)
        batch_op.alter_column('scene_prompt',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='场景提示词',
               existing_nullable=True)
        batch_op.alter_column('voice_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='语音类型',
               existing_nullable=True)
        batch_op.alter_column('ai_platform',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='AI平台',
               existing_nullable=True)
        batch_op.alter_column('scene_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='场景类型',
               existing_nullable=True)
        batch_op.alter_column('equipment_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='设备ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='设置ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('navigation_points', schema=None) as batch_op:
        batch_op.alter_column('enabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True)
        batch_op.alter_column('rotation',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='朝向角度',
               existing_nullable=True)
        batch_op.alter_column('y_position',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='Y坐标',
               existing_nullable=False)
        batch_op.alter_column('x_position',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='X坐标',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='点位描述',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='点位名称',
               existing_nullable=False)
        batch_op.alter_column('equipment_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='设备ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='点位ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('has_error',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='错误状态: 1-有错误, 0-正常',
               existing_nullable=True)
        batch_op.alter_column('is_offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='离线状态: 1-离线, 0-在线',
               existing_nullable=True)
        batch_op.alter_column('usage_rate',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='使用率',
               existing_nullable=True)
        batch_op.alter_column('last_active',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后活跃时间',
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='IP地址',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='设备当前状态',
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='设备所在位置',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='设备唯一标识，如G1-EDU-001',
               existing_nullable=False)

    with op.batch_alter_table('education_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='更新者ID',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('navigation_mode',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='导航模式',
               existing_nullable=True)
        batch_op.alter_column('interactive_qa',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='互动问答',
               existing_nullable=True)
        batch_op.alter_column('hand_recognition',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='手势识别',
               existing_nullable=True)
        batch_op.alter_column('robot_action',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='机器人动作',
               existing_nullable=True)
        batch_op.alter_column('voice_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='语音类型',
               existing_nullable=True)
        batch_op.alter_column('subject',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='学科',
               existing_nullable=True)
        batch_op.alter_column('ai_platform',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='AI平台',
               existing_nullable=True)
        batch_op.alter_column('screen_sync_mode',
               existing_type=mysql.ENUM('auto', 'manual', 'off'),
               comment=None,
               existing_comment='屏幕同步模式',
               existing_nullable=True)
        batch_op.alter_column('equipment_id',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='设备ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='设置ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('dashboard_statistics', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('total_interactions',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='交互总数',
               existing_nullable=True)
        batch_op.alter_column('total_tours_conducted',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='导览进行数',
               existing_nullable=True)
        batch_op.alter_column('total_courses_delivered',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='课程投递数',
               existing_nullable=True)
        batch_op.alter_column('total_error_devices',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='错误设备数',
               existing_nullable=True)
        batch_op.alter_column('total_offline_devices',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='离线设备数',
               existing_nullable=True)
        batch_op.alter_column('total_online_devices',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='在线设备数',
               existing_nullable=True)
        batch_op.alter_column('statistic_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='统计日期',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='统计ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('courseware', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间')

    # ### end Alembic commands ###
